apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - frigate/ks.yaml
  #- nextcloud/ks.yaml
  - wordpress/ks.yaml
  - wordpress-guests/ks.yaml
  - renovate/ks.yaml
  - omada-controller/ks.yaml
  - ejabberd/ks.yaml
  - unifi/ks.yaml
