apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:o9jemLIZOsVQ9KBHQ8O7HXxid23uye+3z2BDTbwcRXu+lioY3aZwC7joJDZpTWUId94qbRfc64k2UUW6eB+4K0tG5ck2iE8qDJmyO8AiJ+zCYfgXwmWYu49ZKgWTMg7nxK9dDmrGnKuWD00DnFp7go7pao9MYggxVyzioazcpLk+aqzuzAcyZrsK/WT/KPdXne+VhuOb2WoIhd9Gscjr3KnTkMk/6HE+CvO6uZzS7HPXqldITY7CV3JTXGyxSBqdcd+04I2wCcprCWtSngviCBrYOCEl6bgYvemlpBxlPokodtTbDz8CjbjIQomrJJVs2e/a6RiWCotgdL9y+YpOX4b30yEr2IKwfzT6yqRT8F0dpohwFsALuo+DIisYfPU/6m+KzR5BUse58bB2jbZh9L/v+pwXOLCrZe5F7/AP7oBYF1iGw98qSOeMpwqWlanVL5afX1SFV/5JvSlvOgNeUPld3x6a7qA3K1zWy/a1Hz/SwEwzAUkkLwj46Fj4jTKl9Crd1nQ19wro3otP6pidHexsh6XRt8kYX2ai0IP2Xj+tISi/p9IaJoqRJA9V3vea9p79UMk24BQSJsCxadRhCcXd/+rI68WnyZogzTvrsGKKBwtmkqcFN5uQ86eFz5gCuRMHAghVahJcaljQ5LH13AFWVaO3FB9t/MDV4IJq+EublPCopwCXoVnsX/AG6VoCO3Pg8jCt+Vm7QRKMXnePYUt1UURY4tkrwGy6TzfzmlbxCdLWyO6VKH9r8ql8sGHVY7/TvDQIJG5QuZN5jMy3rNn5G1YvD/54g1JaLDQu7mPHLQs+wAMF84xvQOmtnA==,iv:85NipcRZ0bYURhzCjyTQURKh/nNGpuXYrYq/mLYLzh0=,tag:AHYNcL+zgwybAxW028JS1w==,type:str]
    identity.pub: ENC[AES256_GCM,data:A0pitlm0pt+1Q9zHcT5ftIWO/i7zaJe4siVaTC0ZGy9w3z+db0YU0dsQKgQtiI/suxRVdl1FOTLj8brpcoV9QKcPJGHVIBkzPm+Em3Fq5MDPKGUHSpJTCleq5V+S52MGc9BaQG6XNKuK8Bv7evl+EuRWwjQiGMA6qpPFplrS9sib4HdWB3oZ/rke4dbGNNXR+WkNWMEsSSybc1FyRdB6gcGRVpux5KYHfQcuodlTFiK0+wCkQh/OVZVJ+UUJv0oHu7dIUXmv4iRdVzjM3Q==,iv:eEnYu+xXfpsRzThCXjX09bQfaaSQSTDgSVY8JZ075mU=,tag:xC8h9SZyfdz45PUjZqA8GQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:GmLitBml7sHtwXM27ccmS2NgO+afB1p3tVBENs4R04ciAO6+4S2SKbH2n70IUdil4dF8B09smWbx2jflFDpQ7p73B+79dRQuEAVT00QfrLldEzWqtYkiEwXiSjn49U+0jjBgO2586G/n3F4KHheBBK0jh1d385MVOaSIV1QEgvxmtvW3/NhTOUZgfkSt9EGVKZaiqOXQTZFcbKjye4kmu3R7DtEon7ag5m60,iv:mR6tMW53rMLTIh7MRTp5YUKmhdoR4VwjbVmu5Bv1zG8=,tag:K1hxl3Tr5RNGVc4EAzXgkA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT09LR1JqZk90RCtrWURM
            ZllFbW9scUdGQitGQVZvVHFZY2c2SXZSMmxVCkk2dDd1MXhDYnZCcitNKzZHYS90
            K2tNN2FzeGtVa2pFTWhwdlRMOVUxSUUKLS0tIE9RY0FsSHNTV1lvclloa0o2SlRl
            TFFzVUNzWng4c0VBRWVqcEVFN2tzRW8K86f+uOVlItDH3u2kw8HvTBNfYnrpLNez
            P8jvYCenfDXQZWKBwmtZKNxmyWlaTabLTfaRhq+GlDAVu3jIcoS6qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T17:51:30Z"
    mac: ENC[AES256_GCM,data:Id2iqVCL4+qiC6wmhXBvvjYvVS6BWvd9ZnA6NzUsEnj2d8HQj4Azc3W0yRsgENfXicH1HItFEsKXldl43ag45jzNKvO6QQhdfqTUBHS70z7WTon2hkIxpmwG/VP4iZcxoUBNatoWUGPqlHjNa0t2udk8Hvaahr1DAw585o1+oN0=,iv:0bHAFm+eEYBq75MuA0ChhBkenk1CVV6LzFL2XpZcmYc=,tag:brJBb4Q54BkP08fI+8U3IA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
