apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rGdm1T0+jUDqjw+weufswuS3pYmh7103ux4NnpbVhFkV1RpypWgO/X0LKlu73zusHcLNy7hrLdPl494kcP/gTKWcPAQbL/E+DMxSR+19GmgbAab9Unqa5Gr7+Vmc5Iw2S8QBs6d1vKKeze6WBEg9/ElxwcLRvvwwY1h/IYBylm7dqKUc9/0rEFxoIPjVJP5hT2AQUxUSM83l2HQbHoxWVrqPBd3qGAcVwzDpEpdzePU68WU6nTkNB2WRGif3aJd/ibSUIkoYzSLnGNtRwbJTQG/v8/gGIZtF2fnwo5BYrsybYcOnhgx0zSEkYieiIwhOK1ZdFarnXXzWiS7+XYpi+mZBwR/8Sk+GeKRMW8nux8nctFNbjNocHRruxiiRKFB6,iv:AaRMedSPKeztMCeKDz6iJIwaPhAp2ZGkgei9iBCF538=,tag:m3jj+MAnaH224lzoBWEwzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:TTJNu/MZcDSqA5gZ7d1Zf/MZkQU2B5NjFGZ7lR5kj/pe0/rUidafw657bmW5d9kqbD2oZJNcpNrkPzEVcBLinKzwBWmVlPwsrc0i1eALHOCLEnIwOLMRcZ4GtCR/9LrAEQWovxoduypHf+AnX+wKEZADnzWTHKYKy4a0CocsUFA4H629J64WBLRj8d/cGmugDAxsuwO5+g4ONDAqfPEytAKlek+gzNpLU47NQdIaKp3bVdpLPQ97SYevnNncHsWSD1cQr20YkQwGjmbUMQ==,iv:psCitq0Bnerat3xYp57GyhAlnzFL2Iq5XvLt32M44FA=,tag:p2cC73I/TbUp6LkypoKHHA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZeLQySS94uxMB3PMvZyWvBO86brVSoDIRgHurLAdBLiZlgrTHjojOS/KNLUx/GWop3hhzSramLspGM5W2Pykzwi+avFxLl+LW7rhagwx8tzL8qVfpY2tGKC0ElpPcADdJdRziUVXsJzbGQYAZGfVmFEBXGGQ2f+stRAZXh7huWeyZPcZuwIFXojTZUvxEviRYxOCVxRrcPptNOo+Gb4zWQTLwdryPK4Evi6a,iv:j1IZE5hINnBn3VWmNscuc/kZ/KKSkfhWxa8ayHiJHGo=,tag:3JXvm4YW4MYdk6k06ApwbQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYUJ6VUwvYUVOTmczcWxM
            SzljVDB3cnlZNllaWit1VWw3WHlBN3l0UVJrCmR3L0NJRTA1RVBGK0k2OXR2TVNx
            bWo3dm11ZTB6cUVnZ0hXR0V1ZTR2TGcKLS0tIGZQMWpZc3g3Qnc1RmF3azNBSTNl
            bnJ3ZEkwVVBuUHR6R1duL3NEUXVCNUUKpCRQ3hZtQu1y6d2BKFaahWGwozk85bcb
            AvGWEYpwZNuzI07MrQjUz7TdK0YD5Q9xVYDAV1MB8OsyXfZsK7RFbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T12:37:42Z"
    mac: ENC[AES256_GCM,data:+fZkKfA72QjiKgeiq0hibC4mmJzyWm1flLoVpsWV01B8nbwEZ4fGpKlc3qedN+s6OVsR5epEo6UAgv5DRqPNPmQGCSCNovbHgJ+ckeWSafOymfeaUHDejDA+ohhje+LhU/O0AXJpNZbtdkTi5EV2V/j2WVZ+wVTOO2tQ07XRzTc=,iv:Cxkntw5BfP/oRM6vXIufpj+BWo2jcsPiPVD0ncTmDyg=,tag:0KqglE0vaebewyfoNziYuw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
