apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NXUSv//7CpMSIpkSle83ObCy6DlHmF5sgiOThcD15OGBLiVhYSVDKGFSlHPyfTcTpp1xuQdriP9PYlK0O1bOh1XvD5WjDcGxzJl/4QmVO/CyCwiaOVZEi4mGcz++YqO9Rsy9CWLbVbSdM3NqyTy6VEiPmbQpoHWjGcG1uodk6fiiOhfLPYPa8XX/dJOyVtjImfKCmDUNsbckBmWZpMVd39m3iuTXiiD0HY8W0H5c7ehc6MaAe7ZdRnABK1fcdXnQobwz6e/xOl99HiqMgZfWZnpRmwfbRaTGa2dfJvzh67jM3H4yjiwXHQflg+viJLLMGqi5KWjHPfqSP53KylTfYjSBXRWFnvmw0nSrOKfw6dh9a3iCRdY4Jfm9Jfolmls/4ziEJr+EWw0SpEDXYdHbWzleJc229EyF/J+WPWE+jORjXtd6NN5ftLLA2AmgoDoVWnKfc/ygPYjg7gC7n5HT/YPLZ+E8Q4H5vnFwKfIDZgbASv0xdUdjDdlRxtHfFrWVm92LicSb9KcwkvMPgCn6syf4fijJBCxl02tTDKDH0zszOlqJxOiZFmld4f4jBXdZDwvCKOfPEq1oyc6mVju6gVrDvofHAkvFzRav0HJm84bgQl0rHBNz/Wu3pc6fhF1/hPAajr/s46USwb67oQpaWE/Un6PA08UpBtR1MC8exPPTVGfspXUDqT2f2aYQgXFw1OwioNMRboi59jdqsYffwNXHHtiVZlfH3fJVuzFyC8qun25mowoTVicsuQms1HENmKsSJj2I/CYnO7ugXQw+5c89TvfvM4pwYAjvODwQEd9QZy2Zaws7CfUZZ0uu0w==,iv:ZAyLVW5o/xeN/YCJNAOoPUFdvxkBQFcJV4I0/Pf42ss=,tag:4lX6dv+kkS3hwX9Vkh1r5w==,type:str]
    identity.pub: ENC[AES256_GCM,data:eTjRceeGAKOi90QLHhYvJg9DknCnOkT5rMlm2yIKLZJjIgPrI16/FVLlQsR2PXMXJy/kZ2sTqQ/fbCLKzbJIzv7d3xVroS8VQtKXj+06GPZoYxvH+G0oJ9cLh6t8ti7eGBEvrY7t0Kh9cGrB36VllDnHv5A2T/y9CAeJcjvobQ/hrOwhHGsNKP+yNBsjyhX1YM+SJDryGVRzUHZnOlemlVCvHk3aaIVEjkP8cY0Tv2tjnlml5NAHpFdzrBBtY0DVv/U0WGuFO+Mxm/uYRQ==,iv:0iEF79TzQmj/m+Jg1g8JeL08PwrH5m9rQNZVdi3cTmY=,tag:1n7UuDyOTjZ5Ncw22mBJdA==,type:str]
    known_hosts: ENC[AES256_GCM,data:BYS1+UPjemAkAufH9NMQaGazMTJhc+xSbKgrzTsP0Xt6THuWME0k7YX03j9crekIhdZQRY9RZSPG4GbTehg+oWllOfKLtHtTQrLyJThYdiNlSi1b+Tr3Rr3flOFd0IJwROPUIF+mIdZMWgVOm/4vqHLmSYGIReb9bnLuJ0EX0B/eGEhfupSNvzrOklNYekmT2GVwPeVz5D/CBeTC0FUknvXx05NTdBmJT+qf,iv:GUDPRePcONYAVoTSkg7VNyv7IxkYPohKs70lMNAuvnM=,tag:+axcOeBIrvSErbE8uV+Thg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UEliZnhldC9CNUMvemJT
            UHk3MHUrSTZtMms5K01aSHdyMmVNcTNNN2tjCk9FciswRnN6bGdpZ1M5TnlYYnpD
            ZUNkaHpHcUF5dk5Rc0RSSnNKaWJ1TG8KLS0tIFQweEZRdEVNOWU4V0pmVFM5ZmRP
            MXJlZTVHV216RTh5UHJGT0JQaDRkLzAKaI6dCvC0Q0NhmBujPVKjkBakhVyr3rNE
            vsCC9ostWpoIWKrcjfzDuAJSSS+8kkvQ9W4v6BryPaQRQ/LQ1Ksiqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T12:37:42Z"
    mac: ENC[AES256_GCM,data:GwLG8/KUqI6/JlB+AD5x0ncWvxvflQZqn0p/m/NTRmiVAZjF7aefTHmzONI5G+dRwq5VUHy7Bes1nh7MnABVrMvtRhyFNhcnpHMECUSmOLHIB5ZwZWFwHBkFKUNWXCNOB1rIBIzyehDlbyyC4RGBgcbnuFTZ4e2vuIDavKbmnxI=,iv:Xk5XR4nuxC5KTtsv/p9jhciUj8Q/CuiV/nLWN93ghyY=,tag:qQYudhUcMAFZsRVWDikLxw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
