apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:K/dviNgySF17F142qLKFCIuZy31TQUInFuaZe+8vDY6hLWsgAwh6Q0pbIdHEpeDUko/4Q0ZDqjZwjSrSVK+xvj5G6+gi1selbr7mKaCoy5GpyP3aSNcBP+DpdfN74fBRw1iroWR1GSRhP8Mf145XKvVAvC8LOeUZTtdqtGJudJbHCHi/eFgTRZbq5Xyy3vdVrUij2ah5jSdIAgcz/fyawTXjlbD/NzzxC5PCDn2JYMdeGKYE+24H9O1fIWPWgpF3k0/sEMdjq37rsDgEenmw9BA5vqXaxHiTFY2m432TYfmYMmck91OXOa5PsX9qXh6AaIkNJsb4JDG0ts4AhJXH81PBk5CDgLxE9d3iIZlkuzewSrHapxDw1M7tDHXk8G/x7if7TLN/FFswh11pHmvU08kIxaGtcczuYE6TCujilrNvnNv9d1baocfQXG3aRhBFklSwCbO2vbHYlFt/QMzBCgPEiTOuw2uPI2l5wK3QiOJWsMTz5PXTm1lkqgcbCYIUo14YqCbnGALgm903yOKGt4U4ESOcG9RoNAXzESEEGQiUy3ZLhWEi+nPIi8qyNqp+Uv8NpC0RQeht6h8LpgUfj60FfrBigpDjZCAF/xobuodd+/UiIUzr9+AMbU0zNcS97nyiBjTmn/dR1Zqnhsc1eAnfpDaHD7zO5XPXC2X5s5zhz7Kclukgp/P0QfgRAr5PKvbT03S+ePnyWsiffkPn2dGWgOCw00yKb67cyCVaFNHYoPz70hh7VBRJ8HGwm3bguGQPZjR53FJm+a49+hnMsOoFttBb1ZLPwZAkpn7FA98hqT+R9ORyQF61LRannQ==,iv:O5jEdlPK4Q7a8lTSYfe4Xs5rYdF66g8IhSOdfaxaDt8=,tag:ArcM5NjowzB8MAzaYdCArA==,type:str]
    identity.pub: ENC[AES256_GCM,data:GFQUzdro/OOPk1zk6CgqZ+j3M+l8xox5Jw7fTUQW9jKsaW5Rqdy3WoZ01OQl74opVlrDkgbCtRUPOSgf0H6Ujl0+bXQNhUFZsui2j6G4gfWzumohli0VUTq11fF31V0Aze/S5Me9D0kzVLVL4veUj2gR/LFxhwCSlOOjKjlX/o5Zztr/aH3n68+q9PPYdI79fkvPW6hjhWqrwFvzAOjtPxJGVJ3b0wiSasq5J2QVSuiZAv4ixPt53NS23+8rvq8ERM8hIj3ZueIbiqf7jA==,iv:5tIc3XaRW53a1Z0htgslPrAlokjKGfahP/tNPoL4cFM=,tag:NzsZIUj36eVg7YdBY0F96g==,type:str]
    known_hosts: ENC[AES256_GCM,data:7FCUIAIpL8UnvYq4K8zIfogXByafTN9gxb7C9sXmeMyWNXdZqhi2Bo0J7q9qaa/rlqIsStH5DxB6vPYmtEat4cRK0skJXFQrS4SA4RjFnfy5vgoGwvqFOFa3CUx4cG3aY5lFfe8jEgt+19SrnOOylsFBXZISPdFzjKP0VXJoS9+lj4ORvNOqL3rBr3mGH2zh7Gf69wmciWCcINfaWcU79TjPHJ9KqturByU1,iv:+frGWHckhxmrGHU5A+xFy8CS1CFbENG0U+vd+n2DUAg=,tag:UcChbxKApjkequKl/GCjdw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSmtwNi9jenFiRWFKMHkv
            Rzh3eGc1TmhtekI4MnYvYjl1TzBHQTY3TzFvCk1QSzA0VG41Y1ZzOGVYUDVpTThD
            MUovT1d3YVBabjlOZjM4S0FHd0tTQXcKLS0tIFk5ZVQ2bk9SNHpMcnlURnAyajY4
            eTBJRDN4ME9QUm5FZmY2S3UybE9BWGMKVnVSLOiJ5qH0jLC8nnEVf/UMu2wQ+2Zk
            aZWelRwREQzg6Yw3CiJ8qhx1k6CrNGpaEBPPHtQkGC67gHocd9M+bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T12:36:25Z"
    mac: ENC[AES256_GCM,data:wkbk5tWL1R21Ri0RkFhr+76+bUwRJHRsF66H7TiPtrFzAJlW9VKU2ra9INFq8jnLYyP369mT/boy6lgTctWOqtXru21O10Zc8tigjWpfKXS8Q0I9eM3/BBpzhI2hr8ejCaleKFSh5hrllCiGS84dw+RJdCAGv2maV5SoWZlOzFQ=,iv:dym3vfZTEgUu0+En7Rtruv1uemMS6uEyk/4MRE5wNpU=,tag:dgxEF3R9YZOcIrhJRkCg+w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
