apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cs9rI+1FcpvPjo/VwHDfimuhBmN7Y97Oqdexwtc4jCPHgmxCVgfxQ1kDZtV+8W44sWut+JXe98UH1PIrY/AHNz34oG0q7LvCxwdT+onaXxPOUzzVo9+HmF+GV96cXNNBbN3VPK0xH0llc+lkICNJ3qaowhWJIEpOnDFohmEHZTqIpp7ub9UMoNBSVtBL4hMsCDjNsoH6ux6i1QL38n6/dRb9JERG+CkE2GTnJxvl30XjudDdBUxvPagDcERHsD7+MxX4NZ7VcH34NOAuB3uxFpPjONlXR5L/PZyb9vxfL+ZbDjMf1/OSosXRaSNdnKy5KwwD1A73C5fFfRmQlAaWsMZPowxL2HdpBW00oUeIWt4hQoKhrJ/tfnyDkISiox1F,iv:kjEJcnU2PPL7KV9TVk7pG71DQQfJ0SztxPoR9MhafeI=,tag:l84FRLXAbWp8EFxouhE2Qg==,type:str]
    identity.pub: ENC[AES256_GCM,data:xt3BAuZTCIy/E9zxLd8ZRRqdUNbbyYNrftEE83R26CGHXmjzHfjf2BuXhECuKDyLvGupywgvO+VNUV+MkewCokCMVx6WScFOZPlpogdbwLivUV/MVo43Rfyu9So9zO5nhxVLE3qCKsUCvdI6bh9cVxasFWaA3ASc56fjxi9phUunxSd6taYNYVwFyVAQb1z5ZZJjEMcHAZIlnf0rWRh5r8cBknprA30owLa3mVA7jODFDs4nLgvoJTV66YqLvSOJk/8LjErPb1UABB5MNQ==,iv:jglE4hFzET+va2S9Y37qVJA/HpUa8P+Op0vkL1rRL/4=,tag:dGenxJMJz4FoKCYE0iIqdA==,type:str]
    known_hosts: ENC[AES256_GCM,data:00HbyXqOTWiKPOzWYs0xytQ41eVqw1O148ivBE+XUP3LaGo9Zg7rSQJekUC1UZuoxtoPAUmHini0j1aBu8piUkOIeHgDnoxfv8mMsHGopkst6q6dja3RguXE4/iPIZ6Pjx2FvCH6jkFs7ekdygWJgxM7C2B6r3TPbX6YAFIDdBNEtEr9fd20UqasIuEuvpCte24OuMqp/DmP7hpVOolFEv33+nU49fCVRsWJ,iv:kg3FvwkoZTOxArr8bfrChqisKpHWc1mYU2qWKm3lvis=,tag:c680itbRvlMuRv+oxMnuzA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOVprT0dtdmo4Mzd2TFpr
            MWpLYUVXNTA5ZVhHRUFKcGZJYU9PUFlqYWt3CjhXTTczbDdZN0QrNlQ1aEFTZUZa
            RHZCcDIzNmZleVhROVJ0QlZlblhUSG8KLS0tIGhtTWlGWXpNay9TcXc2eWhYcVJt
            dS9WUFpvOFdHNm1SSkNJQ0pXTFgxQXcKleDrTsWdS9J16F2uvXm/MkUWeRq8JHLo
            njj0g1wA3wuGXpApuzWN6HkFjsjoLuzR8FGlURxxZqzgh6qEa/V7wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T12:36:25Z"
    mac: ENC[AES256_GCM,data:VXKJ+Jbw4eZnh0e9UF+EfHWenUfP0APtzKPg5ooITY37ybVFlJKbBfyPb3zpIrF4boR7DVcctTMwJkUPgW8FwYYAl35RDh9AyDkFyKcRTFGEJqy75bKAOUjA3/3oVx10vJlKKgWFLicEFVQf+RcOYD9VN7+GZtZRzkOj3nn6RbE=,iv:2yRm48uYjeUmYxF5zi78Une1vlsLXTPFp1+Tf2Uj2rQ=,tag:g9QBmYRloZNR0VNVLmkfaw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
