apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:p+2MPqfPLoJ2/K45Y/ywDNe2yE6NsIp8t+u6O86CBMN/iZwDvAaLzMbrGyVD23Cq8BVKpYzkyX283Dlea/h6ZyC3BEqJQROOJYStPnnF8A8x01retrwc5nG96pvklKulCB6pPylvXyuN+8Mb/gNv1N1Y4+01HOf8oQVBlPvrRCe7EeR0admOXnw6zCjJS9TK0IQc+KvtnZFtQ0VzsJpXOvgZWs6aLi1Ne+Xw0RqUQybH0cY9i3dNMddmci8xJJ4s9ChmgK0tSN6UEWZYNNG9PzyqA5nbNO/p5GMSBVcyrM0f3WqgoRr1eiIgmXoQIWjwjiWCKRFxFf5NNiwl/LsWOAoWhk7FisbvuM6crEBog/09VM0BjKw5154AcUI1/TAPxJThCgy2+FEnaTwrzuimXtpwz3Z68ll+2sAMkHonXkoA0PlEk8aMz7glL9WojFKjKlepIVJAqw7QGTIwlW//3L4ZUrKOfLCud7YzQT/627tKdsGJwMHG44pBqQtphdMWXyCZdGzxtEZ29cg0mHKopvnmkRFI+2k/KqnrsS3/pPd8QhlCkR63dvcsl8GiIKU7aT44jS1amjKeuZyS8E1hykBVntZ2qW5u8AI8dLc4m3uX4ukIyJbofTEXNYrYmzQ8o2NBeN04+HVxGjsy3wYou3AfvJck5t2jeG0VhJCHXWxa54z369SoEsbGZlyR4kizeNOiSf04Jc+Biu03C+ht/4eh9vIq2Y4awAdnmAr9In8N0Fwe/r9E4inB49wVqnVF0/ttZAPhGycuUG9yoSp/TI1M05ro1q7UW6Fmvi7cThsn+U2t9j79b8PlEE+yxQ==,iv:eg8Tc7aywBY7cNiM9odpEu7L6wcnCrhzEiXXx/dLxm8=,tag:dc1voB6PLO6Dqip7Axh5FA==,type:str]
    identity.pub: ENC[AES256_GCM,data:pEnEo6dw5oNwKYECPG6Cq2g+8TJgbwNn8c2PF9cKSbNoX0o1cA+1DR0PZTIqwA991WsR4BR2VO5OZYcAWHayGDI02I4Oumefl1VMtti3R53U7rkaxRM7pRcH8RA9a3+BgOZDyrdoKbTT8HxXyd4YR6tU5WZMaNHbpG7DZ0W5pXhnmtqCJpSJEJk/SMVQo5RsnUaH14ZWHjUoHDooSDvVw0Un4dzFC3653UEnDa4y3Ume17NLcIQBjEPeQRWKmFSHVyamYcjSRR09oL72JQ==,iv:bcFCJRHYBdpTdsQVPmUUDxaR0zYUEMfJnCqKJyGKMY4=,tag:9iZ1sZES9tSl8SqttqiqMg==,type:str]
    known_hosts: ENC[AES256_GCM,data:6selHDmB8gZFrRtkWjJB5a4iDEhK/ppHzzGXPSabYMEJ4BNEL7i+3/H8hM8U4JCwmCPLC/o1TAoR7aei4qkaM62fR3zPYb/wVFF0oRoRCrmX6OxTqCHofwqoufOdgOjnwVUlsSEiOgI8rgeSBAR8i+bmm6J7nT+bKy7I8WqVpTqQCnzNMea+MZuCkX0m6bPnmzUKiT8rh7xdI0rFthcQarHxZb/QMkvIdeSx,iv:BiQWSsqpTygHEz0mk98XKBEDWKUNK0rMwJzPHzFJiaA=,tag:oCfIi+ABPHO1diHVokEAUg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ3B1cjRSVEhoUWIzWGZX
            NkRvdmRNV3JsbGpoU2JuTHBQYVRMZjFWU1E0CjNMZVNJcXNkTTZ0K0liWERpbjdQ
            eEtRb1ZmNTJVT2VwQ01zdFYrVFN3dm8KLS0tIGNtMkJBcGNLdXV1RlZKRjRxRWNr
            UkMyQkNrdnNMRVdhUkpwWVVHN2cxSEkKYk2IE30lIIOzbpsiOeRY3sD5sx8KCaxA
            rv8cFsT6ECo69vksBfXgnPQa8tLacd2zhH6UDT3vN9un6vcgQoDqyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T19:46:20Z"
    mac: ENC[AES256_GCM,data:hYpWqeTL9JK3lJRozsq5/20Vdp+UMLofMF6ijc2AboMDDjLCfpa6GYUQutbugLvubVA0RD8oPd5/bzcHLhbJKvKW3+knJp15rGz/SceRPj5nNW0E9/dUIlEELNmIl/6JkFkfWLZDg4nLZiebgQ49Tti0ozm+Xk9kai7yjXS8uVc=,iv:AWI6HikAFvxjbUXH2A2g+ehTqE95SyLEC4Nt0DWXthU=,tag:gwke0i/bMLTnksVRlaVhLw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
