apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:plI2+eBFNX2fEuI9Z+QIRazBZSwdOVtcrG2nf1wHhyr/PFNI6ZkjZOWCuzXRLqCZ8fvuXv3bb2lj2gmbrYIR8QezmdSliO6MBjJ4nDSBQSZjyBncZX3Z7fz++tCHaUsXJ06Bp9sQepmLqhQANpbct+wZkBKbqdpesANPutBZss8dBPaA4Z+g/GxNW2XQ1tBymcCUPZsb2nS6CTs2iN3gbFzSQ4fAfsGjgscMlVyMFUau5BPkdv93PTN8R3KN0TY9oYF3edQ0L5cwx1DdgaZS7gsqvPVPoHaHif2OQ1LgmeMf5XAp/eq5zr16XJmhKeVWPQyJgpLLMbBYD25qm9dfB206XWwuHdtA1EH9YuVaJd9RKHNo+HHgfOrfVtOSzFXZ,iv:HIO0IkM3HUmNrkO0cx25fRAvv4bab72778lcwNwM99E=,tag:s4nuCPsgw0bQtQ3nweMHMA==,type:str]
    identity.pub: ENC[AES256_GCM,data:IgO5YFih+k9zLDDUTG+ON1+TVae5eMgsrYzLIi3eEQN7FsyXiPkPfpmAjmMA9qbYXSzbUlavFXSbkGKfdjj7/KvnbqaEU7VEcYF37IzTLPtIrldFLjro6pCP4RSzpWwE1cx8ylgocDL5DWNrF8pVXwASYJE95MyRDAMhpiICYmO/JxCAI9NbMW0AIWAVMDCc3qQnkdlS5vM3FfILBhxgJmD6U2qWcjQK0Evdk3/EFYj1Xo3sZ1dRTGuzWhcyFlwTPCxbgl+/1FYTlNqUAg==,iv:08BylfPplzS/CUnnxE1hk3g0tDc6pgDg3jAwuggBwz4=,tag:Oa9tWxn6bD9grAbp7g2HYw==,type:str]
    known_hosts: ENC[AES256_GCM,data:GsyXGYFEfdRPB7J0UEDs46A0ErG5NXpP2c5PPat9rzv0V3XhYgkjlPRYE7ByWttJcZcKPNF8qsZuDWdBXB6Fuam51n6/AEcCxgYyG8LaC1eykzBLyEi/xNp38xgFjnK2pV4QkKZ3gPMBBolWJCDeS7OWCTaX3gzNgTCzKmTGlfuIfui8C3zj25eoMXF/X62CJ31gaUgmlCvML8PIWMOJ3FnzE2b7NHGn7S97,iv:YD8j3hc7U+m70zQH0ViS+pUCMtzR0fX6zwrir3KO3R0=,tag:fAgYJEojRGvp04UwRQUDTA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMDdQRENiYXRQT2pOc0JH
            cGFIZjNYeGxNUElkN2g1cm5YUWFyQmdSNEhVCkV4TGQ5QURuRGw1UUtvNVV5TWRC
            U213eGY4ZXZOU2ZMY3phbTZzaWd4S2sKLS0tIEpNMllHWDFiaVlGeC9FaWZKekRK
            Y1h0T21NNWZ2UHNtbGZVMk1IM2VMRmMKYniK4X0vhYLnkpBg4wlxLT0THJrnWHMC
            fjxKfWelwB59La9dSN+s1nXRl8P1A4zJFbig2+tAGInTvi4dSl14Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T02:54:54Z"
    mac: ENC[AES256_GCM,data:zWAQL6nz4t6Yn466WQqFlLNnwQEyFlHcwsvUa2Cq4chIaxtnAn8jSit61p2JwDMCDLtm5CPf/sPKxvPVBy5Ls04lw9x0WWhSRH/9ETXjJwNp/bteWOgHMoAMhYj84BHgYQOJrLhCMGGPXJFSoSdoupGDVQWZTpflzmNS1VvNA7s=,iv:D38i2ldUnjPY1QGB2j8mepPwppVGBjH1h+GwM4K0UTU=,tag:MzsLYnL5tMRFlxetxYjOsg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
