apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IlVe45ZVhwXc0QoW4/e4Bd3MxxQyYzvd8hqxEQ2TGmyZxRqjgMIy0gESjFtKtXcb38aiCSDY4YD5nwpw26MYf26U07g/SSKJm7oMKreE/U9pYoVa0u4+ZTbk7/vrXTd1la+2yAGH5LepV0K9Hkn93bWnyENeMayTgLA+mZQFhDk+s2L2GmabU2JswnZtFfHS9xYs80bU2G7kNJEd2kNW2433yQAO+12H1+4ZdhzAc241p1l55mb+zO8V9wOuTFJfLPi6GvNb4AC/NzDiYtZJY1cCe4FGHJQFi605iq8RKi0DuaMF83JmtShAojGkrobr+2fZlgRCiBXxbEFXSfgysypvvt69enQFB7CMqGqctpYzGXBolKpal/45FwPlV/WL,iv:PAnpm+Qvzf88X/FnQjke+PPLyw9Y95HR6Na20AZU7Dk=,tag:lr/I+00iOvKoKzHVrIh1+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:NYsw+B4jMiQ7JRkqt8aiAdXakOOSW/XacnLatRoJdXtA7aaXOQs/lhf+lLjSSAL1jlk2bHq/m16CjTj7Gkyqo7fOYRyWt5CG+BppWiGGfxBJblqRq/FBwzC7T/HiKRP9dNtlAPTIIo2AXhbYMP6oJn77nwiLFsCaTrm6R0xPFSU4lAnvxHGtGF8dXlsGBRYocMjKCb8Yv8h9c6w3jqD8la8OTifgyQFRRByhnPKu0Sl1rp6WpCGHP3XJu1j3lUCmprYQNaCrJt7lLt1v3w==,iv:v6lT2AviYjeFmw60OuydeX1Mo6mXjytj1x13ge5qzMA=,tag:Sw8yoGQH/NYaiP4eJvT2+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:CIO7gk5IU+7gf32pGL3vf/6vPmZtUnkivN2d08z06SAMh/MUgv5Dl+hLLndTdECTzkEjNbOMf1SuDf+7O2xoGuFYbmroMykIThj+kBnmNNVqKLEscdZY9BAnF4m9MRj30Rim3LqwnJUk3FgxqpfgsvNg4LH+sjZMPWdkvGoVZHHpvYp0kmB6LVghIcwdFaoNNWGpPkf7fyvSgF9yRe08q4UHSOhkqaDK1MN5,iv:Pwe4mVajxgFO5reqM3ztwL/I0MAshVKNv9qjNK2XhIw=,tag:gXHmndt0We0Unc5eQz9huQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseDNMZ0FXUmRQRWFOY3Z3
            cEdrLytQV3FqNko5bzNDaGJ2WjF6YmF2N1JvCjF3cjhIT25nL0NaTUVxTGlMTUZl
            NUVVbElrTmEwMWJYUmxIZXRnM2RsZjQKLS0tIHJ2aVR4cklFVzZnQkh0NGNseFFK
            QXhCeGNhdUxoaktwL2pKQUFKdHlsbFUK+kp8tQ2j/DI+d6yeu99QXyJt+B9aZMHO
            YJKc19f9+gOp9MfyALS6eL6cfI7CA7vCSxHNp8OE8vXtMtcURma/XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T14:01:52Z"
    mac: ENC[AES256_GCM,data:n7LalNkpT4K8a2ZCdxwvL7vBfdx38XWFSw+ppaUiYBajvkFTrxery2LKYt/JY1DPiID+EF6sI58M01TWOdckc8vSLzP9JS26bE61uatAbqdtNpBcHuWCG+cjZefKvhLQY4W6SSxa2UUWnP38COLJapOPNUvrK37g7N96LUR62ns=,iv:LsJ0SR4veF3MWpocS4UKS183Gb47UkMDBfyr3qwxA4Y=,tag:p+hnAu8TQf8p1CdCPx3B5w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
