apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:h7X/vidX71SYwDY99d27rTAn9o/xDepISnA2sek5meXrhqd+IietoO4T3tAm8eY8uNqrDBCNNP6DigHSa3wc2q4Rr94i/yAKlR1ksI6191S/Ew5e1O8ym8SoadnUA4JvEoY+76p4V1ovP5E6toYYQ2zajx/sTfIwahTNezDkEjJY6fy9RALbUpPcv90pXEKvzvvjSuPxLbFWjI/jKJHmIIgzq5GVc3E9XsAENeMyIyNOGH9dYNVwALgtvOdh+YcTC7ZXLUvhLZxtvMUnu0qf4zITHQK7wiJK6ispH9DkZmEubQIwwYkmSJF6478T9cHSF1Ru2z/8U8covVLPl+5fkePVOSmRjEoGFFALy6qhLS1hkslewiootHIhoiDV0ejA,iv:dskRZNAzHHzLCnKO+AO2AEZ/ydfWgD1N+t0scPhi8z0=,tag:HxE2p+IJBqLin+K7JY1aHQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:aqAf/8lrm2wFBHuYPYx577/RpR5IRL5KgOIjAG6Kfd86AtFXYcaSzMFiyOoxy4qro2y/f2oUDXZDxjKxjsvuxnuKPoNnEUFIZENs8gCt2tpKTPFGDsW07VsBvCz472mjvraKrO8g/ycDD/ulBy11o4iFRTTPzglUPGffuyGF4E7mVo3oPk0/spwQR2qMEVdvU1j75EG+Ey7Js3SrrP+HLVaQ5vQycoDMsIn60xMykqHCSOzpMMCOwl6aJPkw3Vou9EU4Wkkj0VqfyKiZHA==,iv:oLKKuBcKBbVVYQtKG+f01Fv+IuvgHhaZvq32AIm0i1s=,tag:zeGD6caf8TlVYl/CThKb9w==,type:str]
    known_hosts: ENC[AES256_GCM,data:ymH97liAaD70dfI1yeJG5HaKyQKvc+DwPdaCBMDMt+BkkQsjQ66fGLEsLu1N5DhN6I0LyZK5/uBU+ZS2YE8j9CAiATRPvqQAINYCMDQIztgcJOVcHINmMiMTcvjznZtzY75CvtUIhKfxY+Omi9IIaje1hhYiTSAwcSh4M9zrBq8APGeZG3zvYUmZIXt8hQzBxGTq0RJyrJQVLhtX0Qxj8cByBBDX8ljpEIHA,iv:FGJoeD4K1RMz6QdL7r2mO/Uo2gRF1Fc070dqTtUfGHA=,tag:4xrPbhgoASzFK8d6lTTAlA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNy90ZTE4ZTIxQ2tmYkZF
            S1ZwTHI5cHhBK1U5Vk14ejhHcDlMN25oNVUwClNXcXk5Y1R3ME8wM1pXSE9oOFpL
            WlZWSmZxK3lSSk5KTnZJcnNMTjg2MzgKLS0tIDl3K3RuVGVld2dzNDJVaHNIOU1k
            OVFRUStkbHIxRnk2S1RpOTFWTXc2N0EKLiggio3/SIIcP1xR4ZOrfI8au3XABksp
            NOFJZwQPJ3e+jXjL+kqzeLxLiUSrUx5brg8UQSNGDhsH8L6PHZ6t9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T15:43:00Z"
    mac: ENC[AES256_GCM,data:DT91Viqb/YqEJ5MTyiUcHcjOKpfxf2MZXhKqw4ahgI9eOHxoOV61k1t90bAU3niMby1a6D5VHffOrFFxW3B3uuHJXV3UKEkhA+//tllYqDQPlq99wLrZ9mVH8s/eUhWl+bzgRLc9JvNoHTK4THU0o/IRiKMrCELGoqh6uUA0vWY=,iv:r2m7RV/ZUUKGiW9ay3MgYXhwkF9PYJXuuxVpPfn3s0I=,tag:ILKNqTcwZkkO3cocXe89IQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
