apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:L8w6CzsHSYlGDzGQonTso9KYKGwN9Juoh3GqqOLUXSaS03tiktblvePX++KpXSMpk25PFBKeT7SPkFylfgwUhfTvLP4XCOlZmv6YDrwsHa8odydfUVq4vGp3Ey3sPS4MVfSaQKqVXR7Q9av0dajpPwJ7j2KOV7GaPBSVxGutTzdKI4x7m2jv4/WPHSwbKvfAzFbgBpXT3q7KTM3HLYosg/uwkT4DfPuAwbijbE2hTDbs8b0LmQv5eSaMN34+daVEbhG/I/R2/wbL8p/WPZUJkNjd1Bxowc65b6Wl4Fyl5bjOq5ooQeOvfIWiX8+8I80QIssQ5WIMwjLRLizOAZuzctOkYj+bgFlXY0e7YzeU1ByzJ2AAT9h35fz2QL9Pzwjw,iv:xvX2sMCt/XvUy4EdMboKZBbYtoxV2sUiIVugWqBDwpc=,tag:Sz5l+5o9lL0Ziqw3BA9MAQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:1Pt1isi0GPKaao0KB1tSXcjp+3VDAh2NSY7Icvxfor9EIvmQez9EXmdbnT9DImT87i0TLls4CVqmU17lap50xCjZnOozZwpsl+CnA9vT5oUCmhTkL97uIGSy720xZiROMw3Yp5vH935clq+xOT6ah52JuOuzzaa5fTN5KThXfXI9l9MoZyHeaxDNv5dEXfMJIkG7bhO5wL3Em8aNjarIuR7kbkFjoAULEX9F6m3bM7/pJfUMQifRe3/NzsyFasGPIgPmdZRRymCobQ15fw==,iv:Ezvdc0lOtBVEFx9/rB6sPJSp2I9lkml1nYNNpLjSagQ=,tag:WEDk+XDuIjOStHligy5rLA==,type:str]
    known_hosts: ENC[AES256_GCM,data:bB+yOMhGzadDf5M9zuCINKVnmDtzMhox1H+JRZAG6WBKlLpys1eeRPqS4foc6vkB1tALamkeAWd4tZU4Xt0pvPsm6PvGWNMowunaCbt3tX7PT8J55qHbCOv4xX9pFq8hw3oCSM1eLcyQCdTzLeBNZ8U7hIQjip9MDbxGUGFKQ+6YUsyqbRsmX49CdfA/oTz67HkKlSmd4Zrbj8Qy3mdjr0BdF7u8uTMsWZKj,iv:8ksTeQxcjGCqdFNbyqWBvmVU/H0DhB16GqIc1g4RzLQ=,tag:NSPdtn2yUNNLNuuIEt05vg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbi9wbmJwWUsvbElxUndR
            QnE3STZ2bEZVOTg1K3JnM2d3K0g0dnZocFJzCkhTSHc2WmpLdTBmU2t6WEV1NmVD
            bnFKYTB1bWN6UDIxWDlHdmdMalBYUmMKLS0tIHNpYXV2MGFTbE5KVjMxRVZZYmQ0
            clVJRXBpOHZyeWNuL2lvK0tTZDFydmMKecP6AFDsZ4V0lpTzd4UmuOc6AsuwdiOB
            N+TqtCEFyGQCPZ9H3ks2AhexJt465ondapLzPWE/PYsLdNexWhaYug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T11:07:03Z"
    mac: ENC[AES256_GCM,data:sFZfNQSAvL+IQ+gvax3G8ulXndyog8Tb9cgxfLdr6poCSmTquiuDuzormQ6DbqJDuWJoE34eLWMxfHcbpQfJpHA27MFATdX8wtHsydRRSyQNQIucmYBP/AKRTMkmuwbvaDklszNvPq58St2pBA5fYIy2mxTIkNebB0k5HH+D1ag=,iv:BXiaJvCdZOwWLt8U2Y7J9/u+pn9dvgjc6aUcv8GhXqs=,tag:UDhKg91Nu1c2qyydiS2pQw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
