apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lNv5Dimdacb/4h5iDvYBviN8JLiMGooY6Fx371Zdx1uHNkitL9l4boG21JJWZKlQXFOhe3LEeLBFoV9GBvihRYkOzYSImqzA3gdAcX9U+jU8yOS6xh79LykNaDTfvxN/st7O5wFHKAPHBkhRwxixV6wmnkfmyURnzt00W4T0u0GCiyulpj83ugetXdC9APD02fhZOcrdqjHta+vA544kLZbZL6NqfDRZ/+dgV+71Ysc7DxZY+fMl7isC65FSW3xV1A40rDhvc6NkC/gjNGuWJLv4SUu8D2OyHHHn4bn524aeyRk3oomPeHg20WKPfzJ1H89OA/bm3ljPw69wQy2W0+9la9ehqhc8yUHIBlKLnSOK6MRVNwgFMMYfzPQUq8lgM+Fx4P9LCxMF92Zji68eB4Xr3gwh6NB2BtwcOPvTrJmwv39TicCEdWWYqKHPoR+V21aFuW/zp5KYdCvOfPzYu8b8TwumKeeREsxMdc3Hi/3R5jlgy3Ba+5y4T5w04DSAg/fFecxBos//7anR2NwUpYLXbpySB0+w3BZTyjiSQ/VzItgQr8yFsLi9zO2+EcGvHytPSuMhnX0/aA+ypFv49t+PWqg2p4PmihN8/CJWx4SCriNvP4QUKvTCzEUc6BDbIc4eD8JuSxEsJ9NtnD5a7w6fpTrjBjsME3700DBeMetcLbZb7QKF8adOOwXhYI9eSvRu2sSMD7WBRFI+WcdQv9tAEuanwWfL92WzH2UxcHS2g1uhLKoR9SgC4rdcTtb+VGDm6Ato3fKrgOFlBVw0jBqeGlC6a5Dl2V7moqaZKslu9+Ltz89NQe7cWBbl4w==,iv:/7uQxzFYYphn5UtrjgUQ8J7LRLR45fgPZfej66RVsgw=,tag:Vem8TwxgV3VyX/C/6UpTUQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:NhjFKvTpUU/alk4AUYAqZ5uT8cFTwnppqHdEwlLdKG2NtreJKo4Fe5sKIi6RPCbCpeJwtf5ovrBXUX0chpfZSaiqb8wB6Df9iLoR1VfKNoJhbOvFTZiITTj6qCHkQ3aHRSV9h6euIJSPz4gax5MSQICYNOuXO69QtbhYr+eFPZjO7R3kcEXgxa0JTqNMvjkxehSGXy5RtwYFDTT0ZVk3tlC5d8n3XtwQNggsUnQX+yKFZyCQOaQ3S/2SRoXepyH7kC8LZGqw+T/GXmXnlw==,iv:u/KljU3m8ntSIMN8rBahM/lAUjz6amVSawKd7inPRYo=,tag:MimfJ02BDbJqbVRVuqtoPQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:FSeT5ZE1B9eM16JEy5EHBg/NCNp8sjJ0TB8Wa95LMaKVJlq/HcLdbCuI7OeigCfN75nCtkTwzH5ZjAoF/A5gsgYw4vN14rxFcge2KXMPtppcPIzZ2S52mvrNDNGg656dVgvl7EYhHd8pjLVNLuSsKeOlLD3nLgZFDoIhVu7OJbuzhOde0ZClS9Muc0SPWctl4wpRRPNAAb6tbI/k0KFNOyArOFfgT7YsaF8m,iv:cguvVku3yDq9UURhQ/zQVQ/DpEE5w04R8NfNJgbPxtE=,tag:zgORRG+bt1n8WUWxEKhL0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMzF0a3R5OHFRNm9nenlS
            Q3VFNjFCbDJZR2NjRDkrcTFXTjcveWhLSWhBCjYrMkkzZTE4eUtpT3N0YlV6V2cx
            WFJQc1pzQTVtYTAvd0ZjOWVMKzd1Z0EKLS0tIDR4bk9xVzNLeWptS3FKY3pSUU1o
            N2tWNnFkQ2w0V3Y0U2ljMUN4MGJOOVUKPOXfDIVkT1PDu+65ejgdONHDa2BsshZH
            zYlZXXnWaBH1MaOYNblUNAgjTTsSbw1rcIJz1bjccq3CnUT6Wzv1sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T17:46:49Z"
    mac: ENC[AES256_GCM,data:LuASNI37ZedsREphRjJNdO/QE3cZpiTbrOnCgRiWuS0zvFju79QYjt3NrUZ66xTOxAlHmfsnzPFJOIsA+CZVmKdS0NsxXH9lOu2uqfNT2PPL5V1bzh5d1VpQ2XHvZ5vQnSK6bGWmyxRXHyOzEspzGKqZr4FtQOsmg5dbx4Nkf+4=,iv:N7ky6oMyUDCSbGG9XZ4E4Cc8/1lGwlAD+CW5vUpmKIg=,tag:2spnS+tRrZJpTz+297Jtzw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
