apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3cVj6klfyuchpJm3qXHKjcjn31dWYybhNDcR2ChkXo4pGOekOdlyIto2j8Qqh/gm26nyJEZY1ijK54Svin9T76ffkjMFlc9auURg0APVAdq8So1An7sz9d7Jr4fOJ4+p7+CKRr7ITIqq41RVX7E1umZfoJNRCyMXrBfLFMjSdDR2Jdotqi72fiubvufL5WUdWPiq/7cojvemvzmxmQTAopWK3G8EBZfHvUVw6p7nxVqEN6zI9cTY4VFTkmiRRWYFhu2QAQ3Wn8Ygo3QxOKZ7mTo2hx85m2Y2jwrltfmvjDEsq82HPwLuEBOMCNGVNHzMZul8V/9b/IyUZ5UU8ObVrFRGV73VQ/RL7WALQUB91og4Y0P83baV8FU5q3K5cMDI,iv:60YPCfPJooP1AUKuhl5qLsohSiwijqwZJQHMupFUUeQ=,tag:krUgEY/2ghZDQ21DRzZk4g==,type:str]
    identity.pub: ENC[AES256_GCM,data:4mA8b/JPdegwuIRhPgr4eK3nhDmxlzEMitU6xDQecKIvgLzAnNIuag3DjxCoprIRbFUMM0APt22xdT+hhmOttxxXCu0UCbg5pwJJgR+fPlWJkN8TaEgc+w40BqOCijtb31RJkvtwYrPeHiP9l4y9Tfo7fR0WGPma6Fk/tuIHZJLLBNCP3P6WFJ1CzS9yXkCzEH6zzKKBzfW90+7udJGVsKGcFhGx1JvtkQIDjT3VljVgas78Idhe/fnjCq+5izGoThSRRJWzn9pREwxkMg==,iv:4yI+1p6UJ/lq3yGiUWT70lcjFAxwBV5NmbN3PfXFk7g=,tag:K2jCnz1BpXPlrMGwww62EQ==,type:str]
    known_hosts: ENC[AES256_GCM,data://TR0aWB0Ri3ok+QAieP8AeJ7haXL2d2r24K/rtA+42K/9hgDKQGrZ9iQVdGAZmEnwnh1DPToy/Ih7tS/CNNm1mu8Y9ulaACO0Gb0JNtgaiJBzKl70Oo+9YaxT9goApB/1nlthhKI5n9QrC4g+5VzvNDRq8TFlgq0Fu3NWbnR9dVxd4/SlhDAajBfU9ALqIhl5OHtDl5LndVQdDMWfFp9Qk0g1E8vrRpMUIY,iv:FhRCqjMzLj43IF7ppSOB2FaL094cLkZAxJ3HOc6dzMw=,tag:BFCN88jpFsl271b45J0UVg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VTM0TUtMS2RoVkJUNmRB
            WTVTUE4wQ3BrTGp1SlZHR1ExNk52WUN1YkRnCnRqTEppaVI1aHNZME1BVkc2U1BE
            ME8vWVpKV3FhbXd1bFRFQTJMTTYxcTgKLS0tIFBaVTRMR1V4eER4WTRtL1dNRitD
            VnNNeXJUT2o1eUlPVGc0bGlsODVIQVEKypWLmHEsBNWNzWIDaTI2O/XOc9Oxfvim
            CbAOVxUeGAP2W90gmtiTkr1LTCsIIsdCDyC/xBjww1gsEZ9j91P1Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:10:26Z"
    mac: ENC[AES256_GCM,data:vMMUbNoIMteARax2offtnlmrwWBiGsDQ5VTsLpfLQ1krvisqjiq9HxV4lw1H9hxWyeEC2WcA4t+Pw/LM6oAw+WNHlnOfwjwn7+WwQ1ixEj4FdybOXVsfq3ju4sSgN6As7Frw7sb3RR7mW1thmsSn47zfWG2GO+LqcqTpaCRTBOY=,iv:3OFWcQAUPm2hHZHhmVuEfIunH8Et8LWxi2oP8ll3mSY=,tag:lycZHrCYeOp6RD7sgQ7bRA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
