apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CDGlzW9SWA+bWePsDJtqrUjnP81b+8FX08J5V8DH4E98vFct4S4UPnV1F9cJDsX+AhMNwMk21yIOQN+Ba/bKPqyrWwy08X2ymwVCHftoV01WVpHczuL2FV6sWP1XAroallNQiHAaL7Nx8yIfGFd/r3IM7nPQo7BoK06+K3+3bPV8jyXD0ZyVK/1Rcv0o4xGeZeoG7kB0Pl3BkEag2pG8HusqojcxaFyOLx3zoHkDRfiL06RQvEH+QEK+Xn8+sge87BUXfDQqypyBbhdbKMVPhi0cq5JJQOsyOiL7j/z/hB+7fDeAH6kkgHtzElqeRj1i/vdqJajfSuxGpz04VM5+kETR9/IsAP89HK9ShqGnP3g+wP2jHve16Y0FYliTlJp7pSrbDzOecktzMps6ModMh02DAHscZ6eqzddS9Ha1Pj487vww47zn9cipmMFlfnpsm4efdTZjOwTMcbTfq8S0O7iKyqDnU93fU9WMqx7G/ZGYxJqa+C1Gl8ax2Jol74lG6sV/WMcdYm1R695kBP0GnKglIgqX3iFfmAbpW14qOJMqKD54VXlHbFFtwGB5kT/FDzcw10HAwrfr8gUUxGJmZ0eEDGAeUzLoPEuGwygN5q5X+przTo64mLlz8JJYbUvPMG1xIgLrirVXSAMJMLXZo8GI9Kx+u6wJ0PmJSnMSziVwKOnRED1yEuvO7XtI5FCUykhMvUd14EcFGlS8FUys/O57EURZCl39jhgrreWT1e36aGU6J6GQ1ejMijt1YJHmANfssQxembr55rd1/vol2G3J7OW79khfkGHPBJE2OlNHHo1wdC8sDim87HKh0A==,iv:J5aB6gBqN0R9HUuftta0OEsChnSFb9y9vQ3cbhS7Ltc=,tag:hB8tpzdvGKJE/DgPpQ/o6g==,type:str]
    identity.pub: ENC[AES256_GCM,data:GUjwQP879M6VniywSYH/5ZK8C1XSMy9S5G2q9D3Wjo2l8LQb5LnlSdE/V896nMiz5AuYkBaB/sMOqCgYWJG6VEZ5y7aWmPwe/5AIR7tJfx0hmvfqE4LU+qp/jh/u0wiEC/DyLlRMEP2pNC8SRL3Wyn/KEy/ocb+avAPLiTihn9yLVbbEG/ud01AeUdTvnZ+GHhaAPKMCRqMKmJQ2bA5l9A3kclmlqnIuEpSclxgUi6Ti6o9fRWNElaIjOX0vUsmmgPWY4WOAlcTcQdcKdg==,iv:P5k8DgoVn187joczeKFLEXFF0rUJk58Qa4qavfxc+k4=,tag:xR7+5b4CjIgT9S3Y+luv0g==,type:str]
    known_hosts: ENC[AES256_GCM,data:QY55fpK9/NHLWvi9l0AdOTk3D/C4YuvI4XpJ0mAa/cSL3mMcGjTOH4fKXid+Jc9pj7BTG7oN0NcK+uCF/1DwgVcZ7p8hDKNnenLLuDBMtN+irq+cxO2gQqwZWtuDu7YvtGHI3Up3hJBAU5wpD6eg6MIrlbOzygk5qiO9WuyHCcqtJ7G3f2oVyIalvNexuRzaaOfudL7nj/d1Rvq1rmg7QOE7aGZFu3lUDEZw,iv:xSTZF7la4ERQOdpBdXrLS2stFgWAlGH7F48Bv0358d0=,tag:/w8HnDoTz5grwrlISJatqw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNclBNU0FMSGdSYjdBd0xC
            NkwzUktRbEo0dGNSTFpEVU5LRURNdCs0VGdJCmdLekVtdG41UndRZEdsWXpCRnpK
            S1BDdzlrRUc4NWNCbHQ5L0E2bWxpUVEKLS0tIEd6cEVKRlJLaFhWWjZiTlBWbXpQ
            bTl6L2x3N25YZ2s3dW5QZ1laMkh3MkkK16r5jXIqeHi3wRI96URCxLeFBeq8FVuK
            u77Fd/LzNb1RmaD+KK1DojCC/FFdjcRgT/KQUvqet8cE1WvTLpHtWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T16:40:19Z"
    mac: ENC[AES256_GCM,data:04VbvwRspP/vGsC1RtY6kZ9+Qh+j7K2FJhIZKn7sXIAePdc6XTgfwQuHfj21Z5hg62kjOC7kmWIc29E/RI3/P3FRj9UsR0JCqH6pgkH6Rwf2kwsl2IEKmn7SsNf0zT/hZi02h5OkYZ59FnnJtJsdGRK8VTs3g83YPp4qIGL6ZYU=,iv:Ld1G/JFdC8p4BKudgva6nddB8P154LbAgtmL+A8fPqE=,tag:vUE4gQ2qJewYquMX44EYmQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
