apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RdQEKvsmIAnUnhVA2oZYsDbZp3J1aucitnoJpvKqsxX41esTcKIWSGxSw2gW/5srPKMpboLzhpN3AGn+lhI9VtUlh+Hk9ZYta4T8FU0xosdD9+oXQ22oFAkjIR40uTWNg4WHRR+6jZu2CyL6iX3F2Inn1zTZZTns2g0z6AZlD2nN8OF9mNcyVubB93P8dctRRChR0rl7OOCFGWWutj5LtiTPf8mzLpPfjtP02nIDHx71N/BP5TVxQolSMBz+Q0rGV+Z0UbFn53PTmDPkyaY+gclf+59YmV+V9l08H5tBxUc26NZIptFdmZsAUqxxVDXs9rQf1Yhza1tdBnix+Y+Iu/vOuTCcmD3ucd4jUWZMU943tU3csWrA5NIoBgNKjXPTQaoFO7TFoLbr9IpTglwU/Y+T+SNIQsy90b2DPNk1xPYSngnAKv565U+GEY+0pF2dY2iJ/R0iThM3vqc3gcQTDsEu45YgjBrxWWc+v9aznqZnY41P0JCFURTh8Glf7EqzBByB25mPkB04V4XkjKXO8TZWpRH1mVQE+WkRbPIzjdWUaelhEjbBXCJBjn459UzgMX+VJrh+kJlycbdmOjbIThPzSIOFPeNHrH3kkodxANT+ckf4TgfGzlPr1PiMsqqk8H1PgODKuXSBGRIqi2UPR22Mdx4DHR20MtKBOi5XlughYwKxWu8+zMbFyvmvppdWIy+xK9yTJeykMuzRr3/kujDaWDSYS3xL6nhbCL5l+iPNFUliEE1z7QZz+aEl9aS2C/iuQe+6OJWImoBp1scGe+1UdgVguBWhUwvlRACGp9jF6IyokFLrqCQH5y5IVQ==,iv:h5YT5XHkaLR/5L0RawRxuvPqjnXrxQfRVgK3amlhMRI=,tag:GJNMQ1lx6jWEuMAE2w5JMA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Czr+QQLy1i5FRDiCyLBgZknB8pziihkHbFbcwfGe+VYHks+xrIaaqpc3z90AN76TXEAJiEGEvGx+wt2C8+KzeTBHHJBeFQBRLZgo23722fld2rVKyj5aSUhQKGXUWGtWhRg3twtOcSkor7OxjcPRdKHHQ+g6FgBrMZfj0Rj5eFxEPRRZbBL8o2ILVGz5jAGiX0TbhAYhrLaU7TSFD84utm6yKzpdM3cRt0zlq6pbjqY/ThOwNlYdWrY+NaRtJphqt0+7S+JoXBPlOFsUgg==,iv:rTZYHkD1c/sPggNi25TQT2J/qrLlNx4ooNUNMD+deec=,tag:hKSvpinMkPXCEfoHOiox8A==,type:str]
    known_hosts: ENC[AES256_GCM,data:XmlHLIC54SsGJ/R4YW6FnQEL7dV6g5nOD+ZiOlcvsCD570HUgwz9yS71Ie6htzLSTnXI7hlR6tPNQuSTyFWmPZqHFcaatUFQueJVpqnLGKqdAb7UCvljvRz1jbFTPmsm/8DtFmybtTXBEh/Lsb9EHcS4AKyG8Hy7iFlfDcnan/YDwtRpiRQw5MMupLpOpr6gZMp2FuEKD93L581PBxlLix9sGUQIoC//ut9H,iv:JvA17Wv0j10nYm7MYlabCOkGhIoOnbWFtH+o8+1Vuuk=,tag:SDYEAfL2fuEuwA45WbtyZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcTA1V2d6K1VxeGw1RHBK
            WXlGS2VuUGpBc0E4cnBBMUhicVIxaEdyZmlnCjBtaDhUZ0RHVVVSampIQS9lRVM0
            ODBGMjFPRElDbU51bFpzZ0lqT2oyaG8KLS0tIG4xUGJsVWV1ZnZhN1Vic0pxeWw5
            NW1DU0haMnpBcGJXc3BXQW50SXF1YjgKentbN1kjZo54UA00wfYdrBbermXjuB+x
            8nEQ7SNmPK2bTvaDUjci7z6gaRh3EE0oEEOyNJXVLnYOmUXk+jkZDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T02:54:54Z"
    mac: ENC[AES256_GCM,data:+mPtyhKQpjdxR1DtavCPblEkIZFUe7294L+H4u4//VinHleJoeZZxbhbQk0ubsOqoqEEj9bD0DeNU8hRlKT3DWpmeD5SQJf30EbF8+fdQLOrqwqgqMPWIkyw3D3ZTaLusIGNkKNCqOFdu3cD60horLiIwL+wPTI/qCD29Ay1zGE=,iv:FiguA7RoKunp73y6U/76F9baZDqIHBZ0WGEL33QEsy8=,tag:sDN7XPOmWLFTFYWjIRq4CQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
