apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qLe0mp2hGNslUTVMW2HkV2F9An5JBzTLyp3qA1sVvfxg52wcAgWvagwnFQLByfQq6xCTiMjZ8boy2GWkdto6vhh/Ta/ug6UutHtJumHjYcpLocX8K3BZEHBkdzW0Ly1ckZKDYqfHKNQXWtCS5Rs2xvsQck75lqmQYJQmQovLWdArsD9LTgpeBCEiCnxIAXD3oYDiAQd0RcJqWqug4vVV4qU5a3cswFnf6oXJm94oTvkxS77t5sKgx3RN/5J4CTW/S0JH1nY6HBrKihqqt30+bgT9+Ki3qX2VRFlrW23KT0ifJHe6rPcQ8rZ/M6AW8/Tfg625M1LgZC4VHh+NjOQKwiIprJyBw7D5SuZ6IcFV442uS1jTmarj2ESR/uwpgaNI83YiZhlXyB8+/yzD9OcJmp4Yq70ezrjTgUHw69UbvCekgsMuHFRCHmFlyXdtx5EqLPdEOX9XURgFdDf7fFx7rtkncK0rnCbf1iMJD2S0MO/xrkGBm7rjIF4u2gJ6oKMGl0L7yKZVQatOUbCekGklhS8cYWk4k9vHQwkKcsV9Li0ReD7TMRDnwYcA5pRXrcE1vHROqFX6p6et3ENX5y7PUiztSBfmxIuR5EYLkfoWbiItrUS6uUzw7LDuJyqRjuMx/w01PDUE5o/WvGMTPFACloKdOTwbrEgQ/aBaqccsYMhp1o14sA3jh36F51p3x9zUXjoYKqDW1g7MyYQXlATuh4MxYS9B8zii40IW50KVzq2Gjo2MwFxgyVc9aENT7SIYLkRtEAFB8IWzMdEZ73xau0JESW9NMrwO1cP4Vzk9QhcmgEP4pLW83X2sWDroSQ==,iv:zkM8ng8ifKeBKD6QsjXnpMLVi/BeON7NySnEe4M1u0E=,tag:IQNJkR25DBsf8RVTqL5LWg==,type:str]
    identity.pub: ENC[AES256_GCM,data:1CJBb/ZSwA1IwgL13qdVrGJGBKTsjn/gippS9DISE6pXmF2RZ0QDYFy6VfrtNHcrRYbHs4LN/4QV9pt2ErviFkynSWvMGarfufVBTyz/P1vHew30t8s3sQF1fWQij/uNsfaF+sWNMXF/4/gboG3drZpJN16JmrIIDbudR1k7J2lfDCAR31caiFDrfy+l185RAMsqwvP8qpgP0YqzgMcs/+udzLn16zpRD2iMRHIrJWWo9dcu7hgl7+pfnF6iyLS7ytzyn6N9SPTCEmpCbw==,iv:NrKN9NsxVWET7Q0wPENXozrqLj3abLNmNow91V5pKSE=,tag:X9IKZTKo5RzWFaSG8LQetg==,type:str]
    known_hosts: ENC[AES256_GCM,data:HxMeZVuPkApSo0Xc7qtx00CyxrIMzV9nL+gvFvV90S7zkLZx818iV1xac6F4k+byf2DMIjrhAdXrhYNlVsyo2/EQGgnqaan6ymrGnSMjmsM0cDBqEC59MjxpVKu7orqJjK9mAStVzVrVHHWhFbGk8hpdhK+zNBSYlB4X+eIPgcmO5j11wQgRzyMg0CGCzjVvoP7xo+ArIqvZDVH+CANDyienEFyIhV60whTi,iv:1P+5xOziPiD7fnw9Mpgg/YlE3fZeSotuTXX/48qQauA=,tag:ujJyNSS7a9Af6xXOcXKmPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSXo2c2dBbG02bkNSRnhX
            RzBtWk9WWmFnWENFQUFPYytFZldyeHJnU1M4CllqTXE3Y1NOZzk5L1NjRE4xTzJG
            MllDVEgzd29rZm00S21PRmlpTlpockEKLS0tIGZiUU9wbkd1aHFRSnk2K2tHM2No
            UWxpZm1BN0t2MjBabjFOcFh0bmpUVGsKIzUIU25Iyf/XwCXWC7IeRgYdOyOW3niH
            3kOVuwzEjSSp3Kb0nEuEb3vI8EG89eQm7T1fzK2c0NmpJxFYy02zzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T14:01:52Z"
    mac: ENC[AES256_GCM,data:zSXDZ3du0ViJfPj+bC5l7KpotA1vtqHFgjm+Dk+zO5Mks/UI4WOq39cwTYjMMPFDajV8LFeoFE3Xlbk15lVGGYMhoXIq/mTkvO5uRRmUc71kZcLvNOXyTofWkjWFKM2dp+lKqvLfvnaUNTCrXmXWbcgLxpQY38YsAfUX6hALsgg=,iv:yJb7/luJ9wx+K8sGJD5fEMSRCLGUfhDI8bKPYU68BHU=,tag:eLjlLqI4AeZUYSGKOksAqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
