apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SmHOOdIsWOt8VwShJ3whUG4E0LA/wBeAP4A7/wxeeNgsNPNBzoslC25re65C/oZr9IbCjCNYIixxDeE+OWUr6nzI9JIaSmBgpWVIVatkO7nxxG6CqbLnrvPpJbVAnwA//4igJ098vRDm1SNTeURNSKpj2CH/C/AGTLZSMQ+lqnhNuyKriJNfeZujWNx8r54LA0h/wECo94vXip0m9yR4dCW6LC2Qd1E6N3E2djLnJSAf02waRgMdCIJMe8O3jLHWV13A4T2OJT1bXfgeWR0sMz1R3aJYJVD7UGy3Kg8VZsy/VSFQF0mC9ehuFwEcX3xcCgGeF7Oo4KDJUR5159jkB1EnDYPWT01VRObYEkzupq6xY+HfI4316sn1eNsXcFCD,iv:3ytSCA7HIhYL15lYGKUFbSZhv4M65Cx/QJ648Y8H1Ys=,tag:p38MDhhAglW8pNkgcS5PmQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:vNHHgxOhPbtFDfT0lN43EasvE8eSn0l6Jj27cpnWxauKFvKkgHsv8CzMiuj9uto83eOb58P/YN/x2KyP76/757lsKvLdSKLhGJuFa4ChFOqYKkqvBVVlYp2IzIcqY7+Sm2ZSQISRlbxp78BvEYfTwBhSQjipLTQtBkCAZid8h7dGgvHIkbZViUXBIV19aEP6Gpp7QC0OwM0bFfJAQnPRBxtCaiSlw4O4gqLoebogz63Q/StqvnpXzvDxTxCTb1Ei8TAvj7EIm60qgwaXcg==,iv:atU8dpwSduD33eBhTV6xXir7atBGEexTWtQ/XF3PkdY=,tag:iRpXTTEag8+x31r+skaXOw==,type:str]
    known_hosts: ENC[AES256_GCM,data:6SleKi+cFlCm5G+R2U/zk03zV+b2BZwOhGfv5umzl7svKwM78vqyTgXw4Hlh9kegGpzjObk8d6Q75ZpQXaQeWJQBREiqEqxZwekATqFfVtxQ9Ht2k++w5at0nnKibIB56/xDQYxw/ZKx5sSxoNeIwjZcb9EYYC2dEmQ1+gxNe+OVgCHiCacucnRidDSC0qfRm7Z4FqW8Ufjgwm07CRLc5SlmIyHSeJzEyxFt,iv:OHoJ0ei2d+H+oYaiRXlfF3VJX7TtKN9UpRbOh+qfxXA=,tag:vWT0o8BLgkeB8MnDgRshIg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RnFVMUNEYmk3TmpQRWNS
            N1NTa2d1R0p1OXNGYXJ3V0hCazc0QnZ3RVZrCnpOMXltaFFTYzZnZFd6S25OaHFE
            ZkpvMTYvS1JFT2FTVW1yYmlQSk5nQm8KLS0tIEt3VXl5a3ZyMHNKR2lsd29UNFpO
            cDRQaUQva3NLTEhEWFhncEJXZHR0akEKIBaUGHhuhk8lBgD7i9tHT95K5nFOeWuO
            GYa35EzuvRy7q+9Nnz3Pt085MIKaATqF+z5y53gy3SDfuExoisdCEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T19:46:20Z"
    mac: ENC[AES256_GCM,data:7C0NeW0LpuDyteizE2l0hayLXBnYeR8DKnnd8p76ovbbq0CBxf+CCM/78WUvZZj2jzuS1lgMMCXD+jMTIwigmZRq89uEOQEm6nhKAQ3WJZPJYMQouLvSf2/Fi6Z+fdlVBQVmQexgpxTdvlcP4tbqQU/+aX7+VPoPR2UteL95q9g=,iv:zHLCcD9XZ0omJW9GcM9GftoM/n6aKSILY8HKIMe8HK4=,tag:4wrIJLktfefLSEu2gaI4IA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
