apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jecaBLDywxkyu8I6lvDblO2KOujlQxIdyd3eJByY3QewgQArhd6YlyzYrVjchyE2xaZ02/adS9BmQW4z3aeXw8WuUPv83WjcQ2sdCovOLsLqxINLsR82LBCbZVvD2+iSVqJsQ1F99BZNYUxcp+p0F/zDxS+k3S7Q4/8nCqbyJoBxwUsD3wNRuZ/iD+nUlgcwG16e4bLaECeqbo0SpVlfERFlS7OGjXsDD9aMcaZzgWhLwt+/ClwdnKz6Y5lgd9Xh8ebnLUI000nuqoXrDCzVEyCmIDuoVbR25Q//y4Ns+0ixkpSC6GxKXV7cJwVXVnshzaZrNn44481WcIe0Q8gKoa0+8MnZofxDBP2fk9Q/MabtzTSfR8nqZSk2+MsUdZRU1gffAf+EeWdvIb33qhF5cCyg/giGrwzLShaLKSHZ6kw7g18gY1nPtMaOep9kaDonc8mjLCK2atadHd4/uFMpqbuiMFhKy9glrHdQGb69BgINyUquVFq7LyaEiG5kkhyWF+VLuJL5XSv6C/HPfAgcnyxqV1dyYtGYyQXfH4RH7V/GuvT1LrRhE2UEAdBBO2KQ2Om3QY3flZ54kIUF+db+aH3yM7QYIisXA84ifiz3KTt99JnVkBvmzRfmx0bWUn8rlTFQVqL6IzpHQEgMmG0JCNrALhnepYec6/aCRFng3srxaXWdvI9tVIp7HzISPYy0QddEA+kqsrY1FC0L7yP7cPmKTlBFP4M4urJ22x4uzOA6TrBKPeGkHD5+uynCiloxm3kLmZlgcoqnfdJG6rXXcTlSXy7NPmxju8apTqp+tcRQkF9KO1yenCgTsgOWZQ==,iv:t3XPVmjGuBUcG/9+HNr4sDrNMZ3Y2ubsJ60c9FZJR0M=,tag:X9hQeSpHIQR0Gg6v4OruhQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:g08PaBEvRGCjkVeBX72QlKY761b75Y29PUlQTxaFBY7CGfSYJgx3Kpm3szvzjfHm3sBgDcPXZen9r/pyKykZ5niaIr1vYj4yLQbsew1DsD904J6znnxY6eNcHZ7nwth8Mn83JyK+N9Hn+xKpzD6KQ0qtH0dq7g+u9SS5dLOE97HEdMm+vRVrPyWD+IiVjsaNAUdNjbNuO6l8gzh9rxQcOyJnGDbF2eLKOJmcmJReoBjo7hPzE82r326GKhzn+sdTZKef16LEWfX1K5JKkA==,iv:ZXGrhgI4hTTPj+p9abo1qKBaqne9TEwnD1Ir019JCaA=,tag:hlua4DesaqZQSbP3PfFVCA==,type:str]
    known_hosts: ENC[AES256_GCM,data:+bOpdkvjTYwL2Mk7jMfLpl+cRRxaomf18qvbZI1hOIkmSnEOKkeXtrxx6cJOvRZc7vJk85ajaYlfoqfL38S5pLwLsHrRAfJMgUESfByclEZDXr+yi5X3JeKyAAlwBzRP0Q/RdpmJ5sVKMWbJaxmf5r3TyjvdPafTD78JWcyuJ/NXAkkyzKYp7SD30apg5sC9MNABf9ELtlDzocAwZrnW+iLqhNiRktfxjpU/,iv:mlFhLGJrka3gKHqjLGZEXAHYcGQuecDWh6FYmjHNHNc=,tag:MafHraaXD1WK1RX0YKYx4A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS0ZZcTZwZmxrRFFuWi91
            YjVlYjVXRzVEeUdoRzhIY2NBeGlXU2huV0FvCkVNN1RCVmY0dEZ2eEpHTEZDTTVs
            Z3EvNVNLZEN1VzdpSm1TTGFCOTdIdVUKLS0tIEFSYW1QQUcrQzRjSUFyVnM2L2sy
            cDhSSDkyNkdoUnRwVXhKdUZ6T2tnMWsK5OEPHxSdzbyRR4yB+oUV+lvwc9J9z8jz
            fX9+JMkpvloceqKaKELM3+3qtgvOXy4OjYGm98tSP1iB3ueibCA87Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T11:07:03Z"
    mac: ENC[AES256_GCM,data:3hq6zy+W/tlcm0XLrD0054nv+CDT4FGNktF2tR/9wp929fj2gno+ZdrDCNXol4n7PeHqZEWK20lzxVrcUfLySzkW1blWJm3EL6x+w5FC3Hhq6TDkhoL5VOPRkYGnHV3qgjKULNdLlXhvamFcCgyMUPccoTvmP26upnnZO3Dv5TU=,iv:3W2Wl/DYg7vUjBxKg36spNgbEIU7/ALduPTCV+dmf4Q=,tag:XPxF8lYQqwvB5LQoElwCXA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
