apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9FHeC6EdPDgbIevyQp0XYMXCZYsHT+H52FvQNWGnfkx4HBbnSbisjSj78tlneATo/UIm2tm3LkxQSxVCyg6+UX1aTGPBrPztA5lUuTV/0SHtyFssGGJ848vbBGDxHkVTO9PC2tSlnYJxKsBeZ8M8i1q0ujvQUcPzyk0PvSRk7dDjHkYBTXV8EEpXypgKLi+JGUGVriszhUDzQ6D0owTXW5hetYN1yswGZT0zI6xHxT/cH6bRUwiyU4jKwQkWe4gVFVGo27iMHTLEccjAEKnpilv7nd+JFtHxxLjwmuxUxdJK2vuoj+0BJGvPmMJHzyVviC4x5t6JI9cdh2utP+2Rh7Rk6inWz+ReIgNywwR/O4qV7ZOFHDJzSmhSoShQdTZA,iv:s9ykaf7e1ms7gZd98MPtlBkTQsyLSxo/O1AmIpSKzyI=,tag:Rkz+TmEQpdiLJjF+uFogQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:tZTw8kH68lr+PRFObDXo6wKpKy3b8Wx8x6BQOrHWh5INyntayBCI3NOXkXHKwz7wjil7j3yh/JUx4G/c+2M0OKB2ptWMdNgdcWDTTpl3ciNm/gHzPoexvoygkrPvWLvrMFzI2NbvEnNfWtH6rCOGIQ+YsGJLKEW5KmSehTj5F/fqBvRU44FgbPwH3rRkoKUb6QOhobVejlsWcUzss6dkrEyq3HTuPGtxvPfjgNoBMSlGwEarNQNtNF/4Sv41eUDemBVnV3e9dsXNZeUavQ==,iv:Q2FTemEtrzugr3H2VuovEd3kHC+LxoxUamfsLZiryD0=,tag:G7ABxMC6BZGiJtXpyuqQ5Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:lTuh3GjZdlIhQW05Ia53AlS/qWeF8I+i09VE3q7Anqmz1uWDPy10X8gMm7b/CmAttubqYQobX1w+9whQz7DQHYjWo2+1phXm1lWfD1xrGMhcf2WnmMZVgSlAyIfiA1K2IHkhaNgb/B0QrVI+HBGscUPnDgI77Nuox+ebGe/+SaIk5gkA6Hi6/BLnD4Yf3oWFi8pCB/BzMqvNC+f6p9nIA1e3pLZTrayUhcuS,iv:n/enTKofCqiRP7GQBZAdFe6c3djd/vyGdNIqg5zNoPQ=,tag:Cp4BYiatNm2sR1ISoAET5A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUFhXYllMOTRYUTEyeFdG
            cXlTVFcwSmRFOXlwK0oxR1pMVWhWYWlxbHpBCnp2MUk2Q05zeFFvcnFrWUFLMnFH
            WER3QXBqbk1JUmhUS1QrSTBPeU0yY2cKLS0tIGZlTnBJbVlEeGp3dEhHdnkzazZk
            a3dOODZzNXZ6U3BVczhwNlkrWTVPRHcK2BZZRLAvOlvuy4cAukDU9kwqUsDTd1v9
            6TvHJbY132NDLTAlDh7gQQCWV8RNWHcNZDXKVqxJpG70k9uM51czHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T16:40:19Z"
    mac: ENC[AES256_GCM,data:5WVtufVpzheyElewfhzOd2Ay2bXRxPv4oRayQ11LnpZGNXujIsSvca4mwSaN/OXnjybFhsj3YNCW2wc/qKw1HgRxELXisLqFlzicxnK/TzZzO/kF/vtyoPaX6Q/24OKkiQTxCIZ1qa94dx3XzgqGa8kP6V25VhOh9tgz8DgrNZ4=,iv:QbDMVLU0SabyrrrArsSTmMwAz5zM4iRjK5ucGQeZ6Cc=,tag:ghekh2HhNM884yNUE6yQFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
