apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KhcnzfIP59Jnea4G6i+OcMWF9XnytewFHkT/+IzcYzCXMuoazA728uB5glYs1oQQB7g2yJdrMuosQkaKbyw4JoYkO7Km4EECLz4iyLHYsZgdUnyFCDdCvq5I+n27sMsd4ouAQYcO00vI3wJBSP/h72yQpEc1jYvbSa8dAEGSDddNJ9lgDZTZurBikB3O84g3fRaSB4HURtmiLu1MyXpWyabWQo6RlSYbnybLejXhI68ndHsu1LNamC0oRGm60gwASnL4GmrWhETdKmzHR8VoBEXOpKGxXzrPe0fJvwuKH1kd2VNVZWP+r5BZDPTfxdofTuCEHTfu51In5OKbD3KW8h6hVtPv4cTEKHmfMkLi1elj3ybP8JP+Yk0LYOS7M/YY,iv:mfYwVsPkFBxcs54gC7ol5Sss/KeGteiBpCpU7ro8o8A=,tag:Olp6cr8rnP+AUS5c8nxTdA==,type:str]
    identity.pub: ENC[AES256_GCM,data:d2TK6xfbAhD2WNaNEbBLSKnJ2hHOVafLHrLLlrDgPDxU7xrvvdzL/dtf7lnvJq62E2HCcEMemFfy9cF2DlFr3NdbchvB4r0/6QxR3AC0c439iC79gunJvKjDCibEe8kWkxnaKnVv9np1conXCDGsobBy7EpbIK/YR20tZw521khwK2MChkGDRr6vaQ/Lkoyt/ZDnqh1cA4sqRY/5YmBG91422BxAOZZYBFe9MPGN5g0YfO4mtZDulxqohPj6OJsXATmFM7tG8fyFAvjlvw==,iv:sYZyp+zMEZX1yE0opTu7H384vvyKTpfVj+vYRsAoHxc=,tag:pswwK1LOAEXsCctNA9QgGg==,type:str]
    known_hosts: ENC[AES256_GCM,data:9AP7blnOfE8qZzTdKVrLamtxc9O4c5Qal+XV9MVqslCko6a7k5fWkZzpbNJSQmn2/KnrSv0D8gum9ujvT5deILIxMo3OPp5jV33+NsUnd4vU/QKU8BG+v6WwAP/v9CfDkNb/LzQoXRqBP4U8VgpZ2RWhUk6uYofNGCldURjUE3EkkMkJz2DFDr91Z/NqnIDgnSgFMi48l/c9uoW1e9dy163lhSVoqOKyZEBY,iv:a4MBiBKfuSWrAQJxjOqrvmtFPJYo2TwnyyLb0LqiK14=,tag:o+VqJy1/MaiqPeo9HjYw5w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSkVtZDNEMjF0OGdXYnNP
            RmNSa3AzQXNrWTlzM0pFZ0N5SnlIb3hpOGlzCnVyN1d5VElZNEgyZ1FoSTdOSms1
            OFA1S2RNTDlvam5yMkxEd1BzeS9jemsKLS0tIDVLY253N2o3UFhBaTJMejZyS2dl
            eWRORFE0clhOQzN6UnEzbTltaUR1SDgKVz28WWU70MEX9rc6agCMD5bNfFbR8UE+
            RJnsBmJBZNvHZ1RH9l+2I9X8wi/FFcm5nSDdw9mHCerHwsWOEHj55Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:07:41Z"
    mac: ENC[AES256_GCM,data:V6cSpZJWw04GjaKys/GbJPJcPv3lTmdqoDMko1fCFIh1Z7ncdJ/fgMb6Q4MRvQTUzLUfrQweFDSkH0pqRUF0cbck9WXc3v/A0NPxTcZtNXguypjzCzL5/1LFUVJ1MsmQm2NGRQhFwkhR54tm+xEEJBH9Cdjkbm4hxjCl8oO3M2k=,iv:ml96sDLGPJPsHPZtgw/NNVZhoXthPOH/uCdJ5cC7Qo0=,tag:Hvy8a7ztJ0psSrhd+4HMIw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
